### ISSUE TITLE
Trying to pass InputInterface as first argument to closure fails, ArgvInput expected...

### ISSUE THREAD

**Issue by eguerin-ucsf** [mnapoli/silly#18]
I've tried to use the standard Input and Output as Silly documentation says is possible, however trying to pass as 1st or second arguments fails.   And I can't seem to get it to work with an optional second parameter.  

Don't think the documentation is correct here.

<pre>
$app->command('setenv [name]', function(InputInterface $input, OutputInterface $output) use ($myclass) {
    $name = $input->getArgument('name');
    $helper = new QuestionHelper('helper');

  ...

});
</pre>

Catchable fatal error: Argument 1 passed to {closure}() must be an instance of ArgvInput, instance of Symfony\Component\Console\Input\ArgvInput given in migrate2shield.php on line 32

**Comment by eguerin-ucsf** [comment]
This error occurs actually if one of the interfaces are not loaded via the Autoloader.

In my case 
use Symfony\Component\Console\Input\InputInterface;

Was not given at the top of the page and therefore I think it was just constantly passing in the ArgvInput Class instead.   Weird that is didn't say the interface was not loaded?

Unless there is a nice way to fix the error message so it provides better guidance I would say close the ticket.

**Comment by mnapoli** [comment]
Hi, I have no idea why the error message was like this :/ Glad to know this is resolved.
