### ISSUE TITLE
More consistent option syntax?

### ISSUE THREAD

**Issue by Seldaek** [mnapoli/silly#2]
How about:
- Option with an mandatory value    `greet --iterations=`
- Option with an optional value `greet --iterations=?`
- Option that can be used multiple times 
  (the value would be an array)   `greet --iterations=*` or `greet --iterations=+` based on optional multi-value (0..n) or mandatory multi-value (1..n).

It would be more consistent with the arguments I think.

**Comment by mnapoli** [comment]
I agree with you, I initially went that way but was afraid that when reading a command it wouldn't be so obvious to guess what it's doing, e.g.

``` php
$app->command('greet --iterations=*', function () {

});
```

If you don't know the syntax of the framework, you kind of read it like a placeholder/regex syntax and it could be confused with `--iterations=?`.

But I guess there is no perfect syntax, consistency is probably a better option… I'll change that!

**Comment by mnapoli** [comment]
I've replaced `[--option=]*` with `--option=*`.

I have not implemented the "optional value" stuff because after testing it and looking through Symfony's issues, that stuff is unusable and buggy. E.g.
- `bin/console`: `$yell == null` (or default option value)
- `bin/console --yell`: `$yell == null` (or default option value)
- `bin/console --yell=loud`: `$yell == 'loud'`

So I'll leave it out for now.

[Here is the documentation updated for a summary of all the options](https://github.com/mnapoli/silly#options).

**Comment by Seldaek** [comment]
Another idea would be to follow [docopt](http://docopt.org/) syntax, which is already implemented as https://github.com/docopt/docopt.php - not sure if possible to extract the parser but then make it work with symfony console.. Just throwing the idea out there :)

**Comment by ArnaudLigny** [comment]
@mnapoli you should also take a look at the `DefaultRouteMatcher.php` of ZF2: https://github.com/zendframework/zf2/blob/master/library/Zend/Console/RouteMatcher/DefaultRouteMatcher.php

**Comment by mnapoli** [comment]
Those are interesting ideas! It is true that Symfony console's help messages have a similar syntax:

```
$ app/console help help
Usage:
    help [--xml] [--format="..."] [--raw] [command_name]
```

This is a bit more verbose, but maybe much more standard… I think I'll give it a try and if it covers every case and it's consistent I'll switch to this.

**Comment by mnapoli** [comment]
I've opened #6 for this. I'm not sure about the verbosity and the fact that it's less readable though, opinions welcomed…
