### ISSUE TITLE
Alias support

### ISSUE THREAD

**Issue by AydinHassan** [mnapoli/silly#23]
Hi!

It seems that this package does not support the alias feature of Symfony console, this is due to the fact that when calling `$app->add($command)` the base symfony `Application` parses the aliases there. After the command is returned to us, we can set aliases on them but they have no effect.

There are a couple of ways we could support this so I would like to ask your opinion before I send a PR.
1. Defer adding the command until something like `->finish()` is called on the `Application` class. This would allow you to modify the returned command object and have it's alias take effect.
2. Add an extra optional array argument to the `command` method allowing you to specify the argument there.
3. Allow aliases in the expression and add some new syntax, maybe something like `search,find,locate` or `search>find>locate`. They are a bit weird but maybe you have some better ideas :)

Personally I think `1` is my favourite. `3` could technically be a BC break. I think they would all be fairly easy to implement.

Any thoughts @mnapoli ?

**EDIT**

Thinking about it, `1` would also be a BC break as it would require consumers to call another method. Maybe `2` is the best approach.

**Comment by mnapoli** [comment]
Hi, reading #24 it sounds like a good idea. I don't like having too many arguments, but 3 would really make the whole thing more complicated than necessary, and 1 will break things for users. Thanks for the summary and the PR, I'll merge it!

**Comment by mnapoli** [comment]
I have tagged a new release: https://github.com/mnapoli/silly/releases/tag/1.4.0

**Comment by AydinHassan** [comment]
Thanks @mnapoli ! 😄
