### ISSUE TITLE
Single Command Applications

### ISSUE THREAD

**Issue by tim-heinsohn** [mnapoli/silly#30]
I'd find it generally useful to let Silly [support Single Command Applications](http://symfony.com/doc/current/components/console/single_command_tool.html) out of the box.

A simple way of providing this might be offering a `Silly\SingleCommandApplication`.
Respectively, `Silly\Edition\PhpDi\SingleCommandApplication` for [PHP-DI](https://github.com/mnapoli/silly-php-di).

What do you think?

**Comment by mnapoli** [comment]
Why not, but how would the single command be defined? It sounds a bit vague for now.

**Comment by tim-heinsohn** [comment]
Please check https://github.com/mnapoli/silly/pull/31 for an approach.

**Comment by mnapoli** [comment]
Actually Symfony already provides support for that. I've needed that so I had a look, it's as simple as doing this:

```php
$app->command('run', /* ... */);
$app->setDefaultCommand('run');
```

I've added it to the documentation.

**Comment by aubreypwd** [comment]
If you want to use `->setDefaultCommand()` and pass parameters then you need to pass the 2nd parameter to `setDefaultCommand`:

```php
use Symfony\Component\Console\Output\OutputInterface;

$app = new Silly\Application();

$app->command( 'greet [name] [--yell]', function ( $name, $yell, OutputInterface $output ) {

	if ( ! $yell ) {
		return false;
	}

		$output->writeln( $name );
} );

$app->setDefaultCommand( 'greet', true ); // 2nd Parameter: bool $isSingleCommand = false

$app->run();
```

But then running the sub-command `greet` requires `--`:

<img width="382" alt="iTerm2 - -zsh — UsersaubreypwdReposgithub comaubreypwdphp-cli-silly on January 13 2023 at 0550 PM@2x" src="https://user-images.githubusercontent.com/1753298/212442398-28f4eb7b-f21b-4579-8923-09c2045e3e28.png">

...so you can't really have sub-commands (and them operate normally) when you make a single command (default) re-direct to a sub-command.
