### ISSUE TITLE
Question: injecting Symfony\Component\Console\Style\SymfonyStyle ?

### ISSUE THREAD

**Issue by gou1** [mnapoli/silly#36]
Hello there!

Silly is great for quick and clean CLI apps ! So is SymfonyStyle (http://symfony.com/blog/new-in-symfony-2-8-console-style-guide) for quickly handling i/o. Right now, using it is a bit verbose:

    $app->command('meh', function(InputInterface $input, OutputInterface $output){
        $io = new SymfonyStyle($input, $output);
        $io->comment('Aye aye, sir');
    });

In an ideal world, i'd like to be able to:

    $app->command('yeah', function (SymfonyStyle $io) {
        $io->comment('Aye aye, sir');
    });

I tried to use DI for this, but it seems I cannot inject Request/Response in my service. Something like:

    $pimple[SymfonyStyle::class] = function ($pimple) {
        return new SymfonyStyle($pimple['input'], $pimple['output']);
    };

or like:

    $pimple[SymfonyStyle::class] = function (InputInterface $input, OutputInterface $output) {
        return new SymfonyStyle($input, $output);
    };

Eventually:
- Is it possible somehow to inject Request and Response in a service defined in the container ?
- Or would it make sense that Silly supports injecting SymfonyStyle directly in callables, just like Request/Response?
- Is there maybe another way to achieve what i'm trying to do?

Thanks a lot!

**Comment by mnapoli** [comment]
Hi @gou1, that's a great idea! I've opened #38 to add that.

**Comment by gou1** [comment]
You rock dude 💯
