### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by umulmrum** [mnapoli/silly#59]
I'm just trying to get started with Bref and Symfony 6, but this lib isn't compatible yet so Composer fails. I'm afraid I didn't know this lib existed until today, so I just saw that there has not been much activity lately (latest tested PHP version is 7.2, no Symfony 6, no psr/container 2, still using non-working Travis). I might be able to contribute (but haven't had a close look at the code yet), but could you please state if the lib is still supported?

In any case thanks for your work!

**Comment by mnapoli** [comment]
Hi, yes it definitely is. Feel free to send pull requests!
