### ISSUE TITLE
Update symfony/console dependency

### ISSUE THREAD

**Issue by cjobeili** [mnapoli/silly#60]
Hi Matthieu,

In order to update bref on a Symfony 6 project, we need to allow the symfony/console to be updated to 6.0.
I can do that but it will break compatibility with older version of PHP.

I saw this https://github.com/brefphp/bref/pull/1117 and i would like to know if you prefer to still using silly or just use this PR?

Do you have a BC Policy or can i submit my PR ? 

Have a great day  !

**Comment by mnapoli** [comment]
Hey! Feel free to submit a PR here as well, it's still an improvement regardless.

I do think we'll end up merging brefphp/bref#1117 eventually too.
