### ISSUE TITLE
mnapoli/silly issues with Laravel

### ISSUE THREAD

**Issue by icetechy** [mnapoli/silly#63]
trying to install Laravel/valet and I keep getting errors related to mnapoli/silly as bellow: 

  Problem 1
    - laravel/valet v2.18.8 requires mnapoli/silly ^1.0 -> satisfiable by mnapoli/silly[1.0.0, ..., 1.7.3].
    - laravel/valet[v2.18.0, ..., v2.18.7] require symfony/process ^3.0|^4.0|^5.0 -> found symfony/process[v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.37, v5.0.0, ..., v5.4.3] but the package is fixed to v6.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - mnapoli/silly[1.0.0, ..., 1.2.0] require symfony/console ~2.6 -> found symfony/console[v2.6.0, ..., v2.8.52] but the package is fixed to v6.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - mnapoli/silly[1.3.0, ..., 1.5.1] require symfony/console ~2.6|~3.0 -> found symfony/console[v2.6.0, ..., v2.8.52, v3.0.0, ..., v3.4.47] but the package is fixed to v6.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - mnapoli/silly 1.6.0 requires symfony/console ~3.0 -> found symfony/console[v3.0.0, ..., v3.4.47] but the package is fixed to v6.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - mnapoli/silly[1.7.0, ..., 1.7.1] require symfony/console ~3.0|~4.0 -> found symfony/console[v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.37] but the package is fixed to v6.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - mnapoli/silly[1.7.2, ..., 1.7.3] require symfony/console ~3.0|~4.0|~5.0 -> found symfony/console[v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.37, v5.0.0, ..., v5.4.3] but the package is fixed to v6.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires laravel/valet ^2.18 -> satisfiable by laravel/valet[v2.18.0, ..., v2.18.8].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require laravel/valet:*" to figure out if any version is installable, or "composer require laravel/valet:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by mnapoli** [comment]
I would suggest using the command suggested in the output, in any case that duplicates #60

**Comment by icetechy** [comment]
> I would suggest using the command suggested in the output, in any case that duplicates #60

Please can you help me write the commands? I am a newbie to this. thank you
