### ISSUE TITLE
Feature: Specifying a value of an option as a space/comma delimited array

### ISSUE THREAD

**Issue by yCodeTech** [mnapoli/silly#68]
I know you can use `[--name=]*` to specify an array in the command definition. But using  `--name` multiple times isn't practical in CLI:

```sh
$ sayhello --name=Jim --name=Shelly --name=Jerry
```

Would it be possible to specify the value array using space or comma delimiters?

Example:

```sh
$ sayhello --name=Jim Shelly Jerry  #space delimited array
$ sayhello --name=Jim, Shelly, Jerry #comma delimited array
```

**Comment by mnapoli** [comment]
That isn't standard, not robust (what about values with `,`), and AFAIK not supported by the Symfony Console, so not something we will want to support unfortunately.

**Comment by yCodeTech** [comment]
Values with `,` or any other breaking characters could be enclosed with quotes, just how it does currently: `--name="Jim, or Jimmy"`

```sh
--name="Jim, or Jimmy", "Shelly", "Jerry"
```

But I appreciate that it may not be supported by Symfony. I shall close the issue.
