### ISSUE TITLE
[Discussion] Daemonization support

### ISSUE THREAD

**Issue by brandisher** [mnapoli/silly#7]
Feel free to close this, as it may be out of scope for the project.

What are your thoughts on adding daemonization/long running process support, or something akin to that?

I've had several instances in which I've needed to daemonize a PHP script mostly because I didn't have time to learn another language to do it.  I usually accomplish this using Upstart/systemd but we could do this natively in PHP using [pcntl](http://php.net/manual/en/book.pcntl.php).  I can't be the only one who has to do this on a semi-regular basis, so perhaps this would be a good chance to bootstrap this sort of task via Silly

**Comment by mnapoli** [comment]
I indeed think this is out of the scope of this project :)

When I need to run a script as a deamon I usually use supervisord. I could also see use cases for implementing it in PHP, but I don't think this is directly related to the command dispatcher. I guess some PHP projects should cover that already, but if not maybe it's time to work on a solution ;)
